name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      # Cache node_modules
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile
      - uses: nrwl/nx-set-shas@v4

      # Lint, test, and build the affected projects
      - run: pnpm exec nx affected -t lint test build

      # Install Playwright browsers
      - name: Install Playwright browsers
        run: pnpm exec playwright install --with-deps

      # Run the Playwright tests using the e2e-ci target
      - name: Run E2E tests
        run: pnpm exec nx affected --parallel 1 -t e2e

