name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v2
        with:
          version: 9

      # Cache node_modules
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'

      # Conditionally install dependencies based on the presence of pnpm-lock.yaml
      - name: Install dependencies
        run: |
          if [ -f pnpm-lock.yaml ]; then
            pnpm install --frozen-lockfile
          else
            pnpm install --no-frozen-lockfile
          fi

      - uses: nrwl/nx-set-shas@v4

      # Lint, test, and build the affected projects
      - run: pnpm exec nx affected -t lint test build

      # Install Playwright browsers
      - name: Install Playwright browsers
        run: pnpm exec playwright install --with-deps

      # Run the Playwright and other e2e tests using the e2e target
      - name: Run e2e tests
        run: pnpm exec nx affected --parallel 1 -t e2e
